kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy1example
spec:
  replicas: 4
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - backend

  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: container1
        image: alihasanahmedkhan/helloworld
        imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
