kind: Pod
apiVersion: v1
metadata:
  name: podwithnodeselector
spec:
  nodeSelector:
    typeofdisk: ssd
  containers:
    - name: c1
      image: aamirpinger/flag:latest
      ports:
      - containerPort: 80
